// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/B8kingS0ga/Go-000/tree/main/Week04/internal/api/dao"
	"github.com/B8kingS0ga/Go-000/tree/main/Week04/internal/api/handler"
	"github.com/B8kingS0ga/Go-000/tree/main/Week04/internal/api/service"
)

// Injectors from wire.go:

func InitializeServer() handler.HelloHandle {
	daoDao := dao.NewDao()
	serviceService := service.NewService(daoDao)
	helloHandle := handler.NewHandle(serviceService)
	return helloHandle
}
